site_name: memo git
repo_name: alex1dre-girard/memo-git

nav:
  - Home: index.md
  - Configurer git: configurer-git.md
  - Les commandes git indispensables: bases.md
  - Les branches: branches.md
  - Git flow: git-flow.md
  

theme:
  name: material
  language: fr
  features:
    # Permet d'afficher le menu de navigation sous forme d'onglets
    - navigation.tabs
    # Permet de garder le menu de navigation visible en permanence
    - navigation.tabs.sticky
    # Permet d'afficher la table des matières
    - toc.integrate
    # Permet d'afficher le bouton pour copier le code
    - content.code.copy
    # Permet d'afficher un bouton "Retour en haut de la page"
    - navigation.top
  plugins:
    - search:
        lang: fr

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
